[package]
name = "jl-pretty"
description = "Read JSON log lines  and unpacks them to std out"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
regex = "1.11.1"
sonic-rs = "0.5.0"

